version: 2.1

orbs:
  ruby: circleci/ruby@2.0.0
  node: circleci/node@5.1
  # codecov: codecov/codecov@3.2.5

workflows:
  build-deploy:
    jobs:
      - spec_test

jobs:
  spec_test:
      docker:
        - image: 'cimg/ruby:3.3.4-node'
        - environment:
            POSTGRES_DB: rails_blog_test
            POSTGRES_PASSWORD: ''
            POSTGRES_USER: circleci-demo-ruby
          image: 'cimg/postgres:14.6-postgis'
      resource_class: medium
      environment:
        BUNDLE_JOBS: '3'
        BUNDLE_RETRY: '3'
        PGHOST: 127.0.0.1
        PGPASSWORD: ''
        PGUSER: circleci-demo-ruby
        RAILS_ENV: test
        TZ: "Asia/Ho_Chi_Minh"
      parallelism: 3
      steps:
        - checkout
        - ruby/install-deps
        - node/install:
            install-yarn: true
            node-version: '14.18'
            yarn-version: '1.22'
        - run:
            name: Install required packages
            command: |
              sudo apt-get update && sudo apt-get install -y libvips42
              sudo apt-get install -y libsodium-dev
        - run:
            name: Install libffi7
            command: |
              wget http://es.archive.ubuntu.com/ubuntu/pool/main/libf/libffi/libffi7_3.3-4_amd64.deb
              sudo dpkg -i libffi7_3.3-4_amd64.deb
        - run:
            command: 'dockerize -wait tcp://localhost:5432 -timeout 1m'
            name: Wait for DB
        - run:
            command: 'bundle exec rails db:setup --trace'
            name: Database setup
        - run:
            command: bundle exec rspec
            name: rspec
        # - codecov/upload:
        #     file: "coverage/coverage.xml"
        #     flags: backend
        #     when: always
        #     token:
